project_id = "qnkmyehsrrljpapjlhnx"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-low-stock]
verify_jwt = false

[functions.import-vivriers]
verify_jwt = false

[functions.wallet-transfer]
verify_jwt = true

[functions.voice-interview]
verify_jwt = false

[functions.save-security-questions]
verify_jwt = false

[functions.lafricamobile-stt]
verify_jwt = false
