project_id = "qnkmyehsrrljpapjlhnx"

[functions.lafricamobile-tts]
verify_jwt = false

[functions.lafricamobile-stt]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-low-stock]
verify_jwt = false

[functions.import-vivriers]
verify_jwt = false

[functions.send-otp-sms]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.openai-tts]
verify_jwt = false

[functions.voice-auth-stt]
verify_jwt = false

[functions.voice-auth-validate]
verify_jwt = false

[functions.wallet-transfer]
verify_jwt = true

[functions.generate-mascot]
verify_jwt = false

[functions.generate-market-background]
verify_jwt = false

[functions.voice-interview]
verify_jwt = false
