project_id = "qnkmyehsrrljpapjlhnx"

[functions.lafricamobile-tts]
verify_jwt = false

[functions.lafricamobile-stt]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-low-stock]
verify_jwt = false
